#Database
POSTGRESQL_USERNAME: username
POSTGRESQL_PASSWORD: password
POSTGRESQL_HOST: host
POSTGRESQL_PORT: port
POSTGRESQL_DATABASE: db_name

#Server
CONTAINER_PORT: port
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: port
EMAIL_ID: example@gmail.com
EMAIL_PASSWORD: password
VERIFY_EMAIL_HOST: host
